### ISSUE TITLE
Search on map for all activities associated with a specific goal

### ISSUE THREAD

**Issue by dgoodare** [dgoodare/AgileEngineering#105]

**Comment by JohnHarrow** [comment]
### DoD Items
- [ ] When a specific goal is selected, the corresponding map appears
- [ ] Code is commented

### Task List
- [ ] Create Map for each goal
- [ ] Create link to each map
- [ ] Get right map to appear for each link
- [ ] Have correct icons appear on each map

**Comment by JohnHarrow** [comment]
Day 3 - The functionality for the map is done and the user can select a goal and all markers for that goal will appear on the map.
