### ISSUE TITLE
As a user, I could be able view activity items on a map so that I can visit them

### ISSUE THREAD

**Issue by EthanGordon** [dgoodare/AgileEngineering#71]

**Comment by JohnHarrow** [comment]
### DoD Items
- [ ] Map appears when link is clicked
- [ ] Icons display location of activity items on the map
- [ ] Icons show description pop-up when clicked
- [ ] Code is commented 

### Task List
- [ ] Get map API working
- [ ] Add markers to the map
- [ ] Add description to markers
- [ ] Get map to appear when link clicked

**Comment by JohnHarrow** [comment]
Day 2 - I managed to fix issues I had with icons appearing on the correct map. All that is left is to fully comment the code.

**Comment by JohnHarrow** [comment]
Day 3 - The functionality for the map is complete. All that is left to do is collect and add all the data we want in the markers on the map.
